Repository cheers-li/cheers-li-app, pull requests merged in 2022-10, with the labels that each got.

#66 Start profile view
  .eslintrc.js
  public/splash.png
  src/components/avatar.tsx
  src/components/button.tsx
  src/components/dialog.tsx
  src/components/dropdown.tsx
  src/components/friends/friend-list.tsx
  src/components/friends/request-list.tsx
  src/components/friends/searched-user-item.tsx
  src/components/friends/user-item.tsx
  src/components/input.tsx
  src/components/list/list.tsx
  src/components/navigation.tsx
  src/components/page.tsx
  src/components/signup/ask-location-permission.tsx
  src/components/signup/ask-notification-permission.tsx
  src/components/signup/confirm-email.tsx
  src/helper/time.ts
  src/main.tsx
  src/pages/friends.tsx
  src/pages/login-callback.tsx
  src/pages/profiles/[id].tsx
  src/pages/sessions/[id].tsx
  src/services/auth.ts
  src/services/friends.ts
  src/services/profile.ts
  src/store/index.ts
Labels: feature

#73 Use global store for logged user everywhere
  src/components/signup/create-profile.tsx
  src/main.tsx
  src/pages/friends.tsx
  src/pages/index.tsx
  src/pages/sessions/[id].tsx
  src/pages/sessions/new.tsx
  src/pages/settings/edit-profile.tsx
  src/pages/settings/index.tsx
  src/services/auth.ts
  src/services/session.ts
Labels: refactor

#78 Fix white screen if the account was not already made
  src/main.tsx
  src/pages/index.tsx
Labels: bug, hacktoberfest-accepted

#79 Small improvements in the UI
  src/App.tsx
  src/components/dialog.tsx
  src/components/friends/request-list.tsx
  src/components/page-header.tsx
  src/components/page.tsx
  src/pages/friends.tsx
  src/pages/index.tsx
  src/pages/map.tsx
  src/pages/sessions/new.tsx
  src/pages/settings/index.tsx
Labels: hacktoberfest-accepted

#80 Add dark mode
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/avatar.tsx
  src/components/badge.tsx
  src/components/button.tsx
  src/components/dialog.tsx
  src/components/dropdown.tsx
  src/components/friends/friend-list.tsx
  src/components/friends/request-list.tsx
  src/components/friends/searched-user-item.tsx
  src/components/friends/user-item.tsx
  src/components/input.tsx
  src/components/list.tsx
  src/components/list/list.tsx
  src/components/location-tag.tsx
  src/components/map/friend-tooltip.tsx
  src/components/map/map-container.tsx
  src/components/navigation.tsx
  src/components/notification-dot.tsx
  src/components/page-header.tsx
  src/components/select.tsx
  src/components/session/session-list-item.tsx
  src/components/signup/ask-location-permission.tsx
  src/components/signup/ask-notification-permission.tsx
  src/components/signup/confirm-email.tsx
  src/components/signup/create-profile.tsx
  src/components/tag-item.tsx
  src/helper/dark.ts
  src/pages/email-login.tsx
  src/pages/friends.tsx
  src/pages/index.tsx
  src/pages/login-callback.tsx
  src/pages/login.tsx
  src/pages/profiles/[id].tsx
  src/pages/register.tsx
  src/pages/sessions/[id].tsx
  src/pages/sessions/new.tsx
  src/pages/settings/edit-profile.tsx
  src/pages/settings/index.tsx
  src/pages/welcome.tsx
  src/store/index.ts
Labels: feature

#84 Enable/Disable dark mode in settings
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  ios/App/Podfile
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/button.tsx
  src/components/friends/friend-list.tsx
  src/components/friends/request-list.tsx
  src/components/select.tsx
  src/components/session/session-list-item.tsx
  src/components/session/session-list.tsx
  src/components/switch.tsx
  src/helper/dark.ts
  src/helper/theme.ts
  src/pages/login.tsx
  src/pages/map.tsx
  src/pages/profiles/[id].tsx
  src/pages/sessions/[id].tsx
  src/pages/sessions/new.tsx
  src/pages/settings/darkmode.tsx
  src/pages/settings/edit-profile.tsx
  src/pages/settings/index.tsx
  src/services/session.ts
  src/store/index.ts
  tailwind.config.cjs
Labels: feature

#87 [Android] Fix login and register links not going back to the app
  android/app/src/main/AndroidManifest.xml
Labels: bug, android

#89 Add pull down to reload lists
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/components/dialog.tsx
  src/components/external-provider-login.tsx
  src/components/friends/friend-list.tsx
  src/components/friends/request-list.tsx
  src/components/list/list.tsx
  src/components/list/refreshable-list.tsx
  src/components/loaders/ring.tsx
  src/components/loaders/spinner.tsx
  src/components/page.tsx
  src/components/session/session-list-item.tsx
  src/components/session/session-list.tsx
  src/components/signup/ask-location-permission.tsx
  src/components/signup/ask-notification-permission.tsx
  src/components/signup/create-profile.tsx
  src/components/simple-list.tsx
  src/index.css
  src/main.tsx
  src/pages/friends.tsx
  src/pages/settings/index.tsx
  src/services/auth.ts
  src/services/avatar.ts
  src/services/cheersli.ts
  src/services/devices.ts
  src/services/friends.ts
  src/services/locations.ts
  src/services/profile.ts
  src/services/session.ts
Labels: feature
